// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_CLONE_VANECLIENT
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_CLONE_VANECLIENT
uint64_t uniffi_vane_fn_clone_vaneclient(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FREE_VANECLIENT
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FREE_VANECLIENT
void uniffi_vane_fn_free_vaneclient(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_ADD_CERTIFICATE_PIN
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_ADD_CERTIFICATE_PIN
void uniffi_vane_fn_method_vaneclient_add_certificate_pin(uint64_t ptr, RustBuffer host, RustBuffer pin, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_CLEAR_CERTIFICATE_PINS
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_CLEAR_CERTIFICATE_PINS
void uniffi_vane_fn_method_vaneclient_clear_certificate_pins(uint64_t ptr, RustBuffer host, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_DELETE_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_DELETE_REQUEST
RustBuffer uniffi_vane_fn_method_vaneclient_delete_request(uint64_t ptr, RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_EXECUTE_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_EXECUTE_REQUEST
RustBuffer uniffi_vane_fn_method_vaneclient_execute_request(uint64_t ptr, RustBuffer request, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_GET_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_GET_REQUEST
RustBuffer uniffi_vane_fn_method_vaneclient_get_request(uint64_t ptr, RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_PATCH_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_PATCH_REQUEST
RustBuffer uniffi_vane_fn_method_vaneclient_patch_request(uint64_t ptr, RustBuffer url, RustBuffer body, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_POST_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_POST_REQUEST
RustBuffer uniffi_vane_fn_method_vaneclient_post_request(uint64_t ptr, RustBuffer url, RustBuffer body, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_PUT_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_PUT_REQUEST
RustBuffer uniffi_vane_fn_method_vaneclient_put_request(uint64_t ptr, RustBuffer url, RustBuffer body, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_SET_CERTIFICATE_PINS
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_SET_CERTIFICATE_PINS
void uniffi_vane_fn_method_vaneclient_set_certificate_pins(uint64_t ptr, RustBuffer host, RustBuffer pins, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_WARMUP
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_METHOD_VANECLIENT_WARMUP
void uniffi_vane_fn_method_vaneclient_warmup(uint64_t ptr, RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CANCEL_BY_ID
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CANCEL_BY_ID
void uniffi_vane_fn_func_cancel_by_id(uint64_t id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CREATE_CANCEL_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CREATE_CANCEL_TOKEN
uint64_t uniffi_vane_fn_func_create_cancel_token(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CREATE_DEFAULT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CREATE_DEFAULT_CONFIG
RustBuffer uniffi_vane_fn_func_create_default_config(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CREATE_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CREATE_PROGRESS
uint64_t uniffi_vane_fn_func_create_progress(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CREATE_VANE_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_CREATE_VANE_CLIENT
uint64_t uniffi_vane_fn_func_create_vane_client(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_FREE_CANCEL_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_FREE_CANCEL_TOKEN
void uniffi_vane_fn_func_free_cancel_token(uint64_t id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_FREE_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_FREE_PROGRESS
void uniffi_vane_fn_func_free_progress(uint64_t id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_PROGRESS_SNAPSHOT_BY_ID
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_PROGRESS_SNAPSHOT_BY_ID
RustBuffer uniffi_vane_fn_func_progress_snapshot_by_id(uint64_t id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_RESPONSE_BODY_UTF8
#define UNIFFI_FFIDEF_UNIFFI_VANE_FN_FUNC_RESPONSE_BODY_UTF8
RustBuffer uniffi_vane_fn_func_response_body_utf8(RustBuffer resp, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_VANE_RUSTBUFFER_ALLOC
RustBuffer ffi_vane_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_VANE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_vane_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_VANE_RUSTBUFFER_FREE
void ffi_vane_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_VANE_RUSTBUFFER_RESERVE
RustBuffer ffi_vane_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_U8
void ffi_vane_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_U8
void ffi_vane_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_U8
void ffi_vane_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_vane_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_I8
void ffi_vane_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_I8
void ffi_vane_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_I8
void ffi_vane_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_vane_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_U16
void ffi_vane_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_U16
void ffi_vane_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_U16
void ffi_vane_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_vane_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_I16
void ffi_vane_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_I16
void ffi_vane_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_I16
void ffi_vane_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_vane_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_U32
void ffi_vane_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_U32
void ffi_vane_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_U32
void ffi_vane_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_vane_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_I32
void ffi_vane_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_I32
void ffi_vane_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_I32
void ffi_vane_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_vane_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_U64
void ffi_vane_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_U64
void ffi_vane_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_U64
void ffi_vane_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_vane_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_I64
void ffi_vane_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_I64
void ffi_vane_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_I64
void ffi_vane_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_vane_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_F32
void ffi_vane_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_F32
void ffi_vane_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_F32
void ffi_vane_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_F32
float ffi_vane_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_F64
void ffi_vane_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_F64
void ffi_vane_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_F64
void ffi_vane_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_F64
double ffi_vane_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_vane_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_vane_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_vane_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_vane_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_POLL_VOID
void ffi_vane_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_CANCEL_VOID
void ffi_vane_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_FREE_VOID
void ffi_vane_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_VANE_RUST_FUTURE_COMPLETE_VOID
void ffi_vane_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CANCEL_BY_ID
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CANCEL_BY_ID
uint16_t uniffi_vane_checksum_func_cancel_by_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CREATE_CANCEL_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CREATE_CANCEL_TOKEN
uint16_t uniffi_vane_checksum_func_create_cancel_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CREATE_DEFAULT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CREATE_DEFAULT_CONFIG
uint16_t uniffi_vane_checksum_func_create_default_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CREATE_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CREATE_PROGRESS
uint16_t uniffi_vane_checksum_func_create_progress(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CREATE_VANE_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_CREATE_VANE_CLIENT
uint16_t uniffi_vane_checksum_func_create_vane_client(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_FREE_CANCEL_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_FREE_CANCEL_TOKEN
uint16_t uniffi_vane_checksum_func_free_cancel_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_FREE_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_FREE_PROGRESS
uint16_t uniffi_vane_checksum_func_free_progress(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_PROGRESS_SNAPSHOT_BY_ID
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_PROGRESS_SNAPSHOT_BY_ID
uint16_t uniffi_vane_checksum_func_progress_snapshot_by_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_RESPONSE_BODY_UTF8
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_FUNC_RESPONSE_BODY_UTF8
uint16_t uniffi_vane_checksum_func_response_body_utf8(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_ADD_CERTIFICATE_PIN
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_ADD_CERTIFICATE_PIN
uint16_t uniffi_vane_checksum_method_vaneclient_add_certificate_pin(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_CLEAR_CERTIFICATE_PINS
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_CLEAR_CERTIFICATE_PINS
uint16_t uniffi_vane_checksum_method_vaneclient_clear_certificate_pins(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_DELETE_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_DELETE_REQUEST
uint16_t uniffi_vane_checksum_method_vaneclient_delete_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_EXECUTE_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_EXECUTE_REQUEST
uint16_t uniffi_vane_checksum_method_vaneclient_execute_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_GET_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_GET_REQUEST
uint16_t uniffi_vane_checksum_method_vaneclient_get_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_PATCH_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_PATCH_REQUEST
uint16_t uniffi_vane_checksum_method_vaneclient_patch_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_POST_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_POST_REQUEST
uint16_t uniffi_vane_checksum_method_vaneclient_post_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_PUT_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_PUT_REQUEST
uint16_t uniffi_vane_checksum_method_vaneclient_put_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_SET_CERTIFICATE_PINS
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_SET_CERTIFICATE_PINS
uint16_t uniffi_vane_checksum_method_vaneclient_set_certificate_pins(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_WARMUP
#define UNIFFI_FFIDEF_UNIFFI_VANE_CHECKSUM_METHOD_VANECLIENT_WARMUP
uint16_t uniffi_vane_checksum_method_vaneclient_warmup(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_VANE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_VANE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_vane_uniffi_contract_version(void
    
);
#endif

