// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(vaneFFI)
import vaneFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_vane_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_vane_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureVaneInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol VaneClientProtocol: AnyObject, Sendable {
    
    func addCertificatePin(host: String, pin: String) throws 
    
    func clearCertificatePins(host: String) throws 
    
    func deleteRequest(url: String) throws  -> VaneResponse
    
    func executeRequest(request: VaneRequest) throws  -> VaneResponse
    
    /**
     * [`Self::execute_streaming`] for the bindings: same contract, with the
     * stream behind an `Arc` because UniFFI hands objects out by reference.
     * `Arc<Self>` receiver on purpose — the stream keeps the client alive so
     * a drained body can return its connection to the pool.
     */
    func executeStreamingRequest(request: VaneRequest) throws  -> VaneResponseStream
    
    func getRequest(url: String) throws  -> VaneResponse
    
    func patchRequest(url: String, body: Data?) throws  -> VaneResponse
    
    func postRequest(url: String, body: Data?) throws  -> VaneResponse
    
    func putRequest(url: String, body: Data?) throws  -> VaneResponse
    
    func setCertificatePins(host: String, pins: [String]) throws 
    
    /**
     * Pays the client's one-time setup and connection cost up front — call it
     * once at app startup, from a background thread (it blocks, exactly like
     * `execute_request`), so the first real request doesn't pay it.
     *
     * What gets warmed follows the configured protocol mode:
     * - HTTP/3-capable modes establish one pooled QUIC+TLS connection to
     * `url` (or `base_url` when `url` is empty). No HTTP request is sent.
     * - TCP-capable modes build and cache the TCP client (tokio runtime, TLS
     * config, platform trust verifier) and run one TLS handshake to the
     * target — on Android that first verification loads the system trust
     * store and is the bulk of the measured ~1 s first-request cost. Again
     * no HTTP request: the server sees a handshake and a clean close.
     * - `Http3Only` never touches TCP machinery, so it stays as light as it
     * is today.
     *
     * With neither `url` nor `base_url` there is nothing to connect to;
     * TCP-capable modes still do the construction, which is most of the win.
     *
     * Best effort by contract: failures are swallowed. Every error it could
     * raise is either transient (no network yet — exactly the startup
     * condition this exists for) or will be reported, with a better message,
     * by the first real request. Idempotent and cheap on repeat calls; safe
     * to call concurrently with requests from any thread.
     */
    func warmup(url: String?) 
    
}
open class VaneClient: VaneClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_vane_fn_clone_vaneclient(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_vane_fn_free_vaneclient(handle, $0) }
    }

    

    
open func addCertificatePin(host: String, pin: String)throws   {try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_add_certificate_pin(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(host),
        FfiConverterString.lower(pin),$0
    )
}
}
    
open func clearCertificatePins(host: String)throws   {try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_clear_certificate_pins(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(host),$0
    )
}
}
    
open func deleteRequest(url: String)throws  -> VaneResponse  {
    return try  FfiConverterTypeVaneResponse_lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_delete_request(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func executeRequest(request: VaneRequest)throws  -> VaneResponse  {
    return try  FfiConverterTypeVaneResponse_lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_execute_request(
            self.uniffiCloneHandle(),
        FfiConverterTypeVaneRequest_lower(request),$0
    )
})
}
    
    /**
     * [`Self::execute_streaming`] for the bindings: same contract, with the
     * stream behind an `Arc` because UniFFI hands objects out by reference.
     * `Arc<Self>` receiver on purpose — the stream keeps the client alive so
     * a drained body can return its connection to the pool.
     */
open func executeStreamingRequest(request: VaneRequest)throws  -> VaneResponseStream  {
    return try  FfiConverterTypeVaneResponseStream_lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_execute_streaming_request(
            self.uniffiCloneHandle(),
        FfiConverterTypeVaneRequest_lower(request),$0
    )
})
}
    
open func getRequest(url: String)throws  -> VaneResponse  {
    return try  FfiConverterTypeVaneResponse_lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_get_request(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func patchRequest(url: String, body: Data?)throws  -> VaneResponse  {
    return try  FfiConverterTypeVaneResponse_lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_patch_request(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),
        FfiConverterOptionData.lower(body),$0
    )
})
}
    
open func postRequest(url: String, body: Data?)throws  -> VaneResponse  {
    return try  FfiConverterTypeVaneResponse_lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_post_request(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),
        FfiConverterOptionData.lower(body),$0
    )
})
}
    
open func putRequest(url: String, body: Data?)throws  -> VaneResponse  {
    return try  FfiConverterTypeVaneResponse_lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_put_request(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),
        FfiConverterOptionData.lower(body),$0
    )
})
}
    
open func setCertificatePins(host: String, pins: [String])throws   {try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneclient_set_certificate_pins(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(host),
        FfiConverterSequenceString.lower(pins),$0
    )
}
}
    
    /**
     * Pays the client's one-time setup and connection cost up front — call it
     * once at app startup, from a background thread (it blocks, exactly like
     * `execute_request`), so the first real request doesn't pay it.
     *
     * What gets warmed follows the configured protocol mode:
     * - HTTP/3-capable modes establish one pooled QUIC+TLS connection to
     * `url` (or `base_url` when `url` is empty). No HTTP request is sent.
     * - TCP-capable modes build and cache the TCP client (tokio runtime, TLS
     * config, platform trust verifier) and run one TLS handshake to the
     * target — on Android that first verification loads the system trust
     * store and is the bulk of the measured ~1 s first-request cost. Again
     * no HTTP request: the server sees a handshake and a clean close.
     * - `Http3Only` never touches TCP machinery, so it stays as light as it
     * is today.
     *
     * With neither `url` nor `base_url` there is nothing to connect to;
     * TCP-capable modes still do the construction, which is most of the win.
     *
     * Best effort by contract: failures are swallowed. Every error it could
     * raise is either transient (no network yet — exactly the startup
     * condition this exists for) or will be reported, with a better message,
     * by the first real request. Idempotent and cheap on repeat calls; safe
     * to call concurrently with requests from any thread.
     */
open func warmup(url: String?)  {try! rustCall() {
    uniffi_vane_fn_method_vaneclient_warmup(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(url),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = VaneClient

    public static func lift(_ handle: UInt64) throws -> VaneClient {
        return VaneClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: VaneClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: VaneClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneClient_lift(_ handle: UInt64) throws -> VaneClient {
    return try FfiConverterTypeVaneClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneClient_lower(_ value: VaneClient) -> UInt64 {
    return FfiConverterTypeVaneClient.lower(value)
}






/**
 * An HTTP response whose headers have arrived and whose body is read
 * incrementally by the caller.
 *
 * Pull-based on purpose: the core never reads ahead of the caller, so a slow
 * consumer stalls the peer through QUIC flow control / the TCP receive
 * window instead of buffering without bound. `read_chunk` blocks until body
 * bytes arrive, the body ends (`None`), or the stream fails — a transport
 * error after the headers were delivered surfaces here, not as a failed
 * request. Abandoning the stream (`close`, or dropping it) discards the
 * underlying connection; only a stream read to its end returns the
 * connection to the pool.
 */
public protocol VaneResponseStreamProtocol: AnyObject, Sendable {
    
    /**
     * Releases the stream without draining it — [`Self::close`] under the
     * name the bindings see. It cannot export as `close`: UniFFI's Kotlin
     * objects already implement `AutoCloseable.close()` (free the handle),
     * and a same-signature exported `close()` fails to compile there.
     */
    func closeStream() 
    
    /**
     * The response head: status, headers, final URL, cookies, protocol.
     * `body` is empty by contract — the stream itself delivers it.
     */
    func head()  -> VaneResponse
    
    /**
     * Blocks until the next body chunk arrives and returns it; `Ok(None)`
     * once the body is complete. Chunk boundaries carry no meaning.
     *
     * A pull that sees no data for roughly the request's timeout fails with
     * [`VaneError::Timeout`]. After any error the stream is dead: the
     * connection has been discarded and every later pull repeats the same
     * error. After `close`, pulls return `Ok(None)`.
     */
    func readChunk() throws  -> Data?
    
}
/**
 * An HTTP response whose headers have arrived and whose body is read
 * incrementally by the caller.
 *
 * Pull-based on purpose: the core never reads ahead of the caller, so a slow
 * consumer stalls the peer through QUIC flow control / the TCP receive
 * window instead of buffering without bound. `read_chunk` blocks until body
 * bytes arrive, the body ends (`None`), or the stream fails — a transport
 * error after the headers were delivered surfaces here, not as a failed
 * request. Abandoning the stream (`close`, or dropping it) discards the
 * underlying connection; only a stream read to its end returns the
 * connection to the pool.
 */
open class VaneResponseStream: VaneResponseStreamProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_vane_fn_clone_vaneresponsestream(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_vane_fn_free_vaneresponsestream(handle, $0) }
    }

    

    
    /**
     * Releases the stream without draining it — [`Self::close`] under the
     * name the bindings see. It cannot export as `close`: UniFFI's Kotlin
     * objects already implement `AutoCloseable.close()` (free the handle),
     * and a same-signature exported `close()` fails to compile there.
     */
open func closeStream()  {try! rustCall() {
    uniffi_vane_fn_method_vaneresponsestream_close_stream(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * The response head: status, headers, final URL, cookies, protocol.
     * `body` is empty by contract — the stream itself delivers it.
     */
open func head() -> VaneResponse  {
    return try!  FfiConverterTypeVaneResponse_lift(try! rustCall() {
    uniffi_vane_fn_method_vaneresponsestream_head(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Blocks until the next body chunk arrives and returns it; `Ok(None)`
     * once the body is complete. Chunk boundaries carry no meaning.
     *
     * A pull that sees no data for roughly the request's timeout fails with
     * [`VaneError::Timeout`]. After any error the stream is dead: the
     * connection has been discarded and every later pull repeats the same
     * error. After `close`, pulls return `Ok(None)`.
     */
open func readChunk()throws  -> Data?  {
    return try  FfiConverterOptionData.lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_method_vaneresponsestream_read_chunk(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneResponseStream: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = VaneResponseStream

    public static func lift(_ handle: UInt64) throws -> VaneResponseStream {
        return VaneResponseStream(unsafeFromHandle: handle)
    }

    public static func lower(_ value: VaneResponseStream) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneResponseStream {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: VaneResponseStream, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneResponseStream_lift(_ handle: UInt64) throws -> VaneResponseStream {
    return try FfiConverterTypeVaneResponseStream.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneResponseStream_lower(_ value: VaneResponseStream) -> UInt64 {
    return FfiConverterTypeVaneResponseStream.lower(value)
}




public struct VaneClientCertificate: Equatable, Hashable {
    /**
     * PEM, leaf first, optionally followed by intermediates (full chain).
     */
    public var certificatePem: String
    /**
     * PEM PKCS#8, SEC1, or PKCS#1 private key. Never logged, never echoed in
     * errors, never printed by Debug.
     */
    public var privateKeyPem: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * PEM, leaf first, optionally followed by intermediates (full chain).
         */certificatePem: String, 
        /**
         * PEM PKCS#8, SEC1, or PKCS#1 private key. Never logged, never echoed in
         * errors, never printed by Debug.
         */privateKeyPem: String) {
        self.certificatePem = certificatePem
        self.privateKeyPem = privateKeyPem
    }

    

    
}

#if compiler(>=6)
extension VaneClientCertificate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneClientCertificate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneClientCertificate {
        return
            try VaneClientCertificate(
                certificatePem: FfiConverterString.read(from: &buf), 
                privateKeyPem: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: VaneClientCertificate, into buf: inout [UInt8]) {
        FfiConverterString.write(value.certificatePem, into: &buf)
        FfiConverterString.write(value.privateKeyPem, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneClientCertificate_lift(_ buf: RustBuffer) throws -> VaneClientCertificate {
    return try FfiConverterTypeVaneClientCertificate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneClientCertificate_lower(_ value: VaneClientCertificate) -> RustBuffer {
    return FfiConverterTypeVaneClientCertificate.lower(value)
}


public struct VaneClientConfig: Equatable, Hashable {
    public var baseUrl: String?
    public var defaultHeaders: [String: String]
    public var dnsOverrides: [String: String]
    public var certificatePins: [String: [String]]
    public var cookiesEnabled: Bool
    public var cookiePersistencePath: String?
    public var connectionPoolEnabled: Bool
    public var maxIdleConnections: UInt64
    public var connectionIdleTimeoutSeconds: UInt64
    public var retryMaxAttempts: UInt64
    public var retryInitialDelayMillis: UInt64
    public var retryMaxDelayMillis: UInt64
    public var retryUnsafeMethods: Bool
    public var maxRequestBodyBytes: UInt64
    public var maxResponseBodyBytes: UInt64
    public var timeoutSeconds: UInt64?
    public var followRedirects: Bool
    public var userAgent: String?
    public var protocolMode: VaneProtocolMode
    /**
     * With `proxy_authorization`, the ENTIRE proxy surface — deliberately.
     * A per-scheme proxy union (rhttp's shape) is meaningless in an
     * https-only client: with one possible request scheme, first-scheme-match
     * is always the first entry, i.e. a single proxy URL. SOCKS stays out
     * too — it would be TCP-only and silently dead on H3 (MASQUE has no
     * SOCKS analogue). Revisit only if Vane ever accepts http:// URLs (the
     * https-only rejections in `execute`/`tcp.rs` are the tripwire).
     */
    public var proxyUrl: String?
    public var proxyAuthorization: String?
    /**
     * Redirect hop cap when `follow_redirects` is on. Shared by both
     * transports: the hop cap is a security bound, not a transport detail.
     * At most 64; 0 makes the first 3xx a hop-cap refusal.
     */
    public var maxRedirects: UInt32
    /**
     * Minimum TLS version on the TCP path; `None` = rustls default (1.2).
     * HTTP/3 is TLS 1.3-always (RFC 9001), so on that path this only
     * validates compatibility at construction.
     */
    public var tlsMinVersion: VaneTlsVersion?
    /**
     * Maximum TLS version on the TCP path; `None` = rustls default (1.3).
     * `Tls12` is rejected at construction with an HTTP/3-capable
     * `protocol_mode`: QUIC mandates TLS 1.3.
     */
    public var tlsMaxVersion: VaneTlsVersion?
    /**
     * PEM certificates ADDED to platform trust on both stacks (extend-only;
     * there is no replace mode and no verification-off switch). Each entry
     * may hold one certificate or a whole bundle.
     */
    public var customRootCertificates: [String]
    /**
     * Client certificate (mTLS) presented to the origin on both stacks.
     */
    public var clientCertificate: VaneClientCertificate?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(baseUrl: String?, defaultHeaders: [String: String], dnsOverrides: [String: String], certificatePins: [String: [String]], cookiesEnabled: Bool, cookiePersistencePath: String?, connectionPoolEnabled: Bool, maxIdleConnections: UInt64, connectionIdleTimeoutSeconds: UInt64, retryMaxAttempts: UInt64, retryInitialDelayMillis: UInt64, retryMaxDelayMillis: UInt64, retryUnsafeMethods: Bool, maxRequestBodyBytes: UInt64, maxResponseBodyBytes: UInt64, timeoutSeconds: UInt64?, followRedirects: Bool, userAgent: String?, protocolMode: VaneProtocolMode, 
        /**
         * With `proxy_authorization`, the ENTIRE proxy surface — deliberately.
         * A per-scheme proxy union (rhttp's shape) is meaningless in an
         * https-only client: with one possible request scheme, first-scheme-match
         * is always the first entry, i.e. a single proxy URL. SOCKS stays out
         * too — it would be TCP-only and silently dead on H3 (MASQUE has no
         * SOCKS analogue). Revisit only if Vane ever accepts http:// URLs (the
         * https-only rejections in `execute`/`tcp.rs` are the tripwire).
         */proxyUrl: String?, proxyAuthorization: String?, 
        /**
         * Redirect hop cap when `follow_redirects` is on. Shared by both
         * transports: the hop cap is a security bound, not a transport detail.
         * At most 64; 0 makes the first 3xx a hop-cap refusal.
         */maxRedirects: UInt32 = UInt32(10), 
        /**
         * Minimum TLS version on the TCP path; `None` = rustls default (1.2).
         * HTTP/3 is TLS 1.3-always (RFC 9001), so on that path this only
         * validates compatibility at construction.
         */tlsMinVersion: VaneTlsVersion? = nil, 
        /**
         * Maximum TLS version on the TCP path; `None` = rustls default (1.3).
         * `Tls12` is rejected at construction with an HTTP/3-capable
         * `protocol_mode`: QUIC mandates TLS 1.3.
         */tlsMaxVersion: VaneTlsVersion? = nil, 
        /**
         * PEM certificates ADDED to platform trust on both stacks (extend-only;
         * there is no replace mode and no verification-off switch). Each entry
         * may hold one certificate or a whole bundle.
         */customRootCertificates: [String] = [], 
        /**
         * Client certificate (mTLS) presented to the origin on both stacks.
         */clientCertificate: VaneClientCertificate? = nil) {
        self.baseUrl = baseUrl
        self.defaultHeaders = defaultHeaders
        self.dnsOverrides = dnsOverrides
        self.certificatePins = certificatePins
        self.cookiesEnabled = cookiesEnabled
        self.cookiePersistencePath = cookiePersistencePath
        self.connectionPoolEnabled = connectionPoolEnabled
        self.maxIdleConnections = maxIdleConnections
        self.connectionIdleTimeoutSeconds = connectionIdleTimeoutSeconds
        self.retryMaxAttempts = retryMaxAttempts
        self.retryInitialDelayMillis = retryInitialDelayMillis
        self.retryMaxDelayMillis = retryMaxDelayMillis
        self.retryUnsafeMethods = retryUnsafeMethods
        self.maxRequestBodyBytes = maxRequestBodyBytes
        self.maxResponseBodyBytes = maxResponseBodyBytes
        self.timeoutSeconds = timeoutSeconds
        self.followRedirects = followRedirects
        self.userAgent = userAgent
        self.protocolMode = protocolMode
        self.proxyUrl = proxyUrl
        self.proxyAuthorization = proxyAuthorization
        self.maxRedirects = maxRedirects
        self.tlsMinVersion = tlsMinVersion
        self.tlsMaxVersion = tlsMaxVersion
        self.customRootCertificates = customRootCertificates
        self.clientCertificate = clientCertificate
    }

    

    
}

#if compiler(>=6)
extension VaneClientConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneClientConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneClientConfig {
        return
            try VaneClientConfig(
                baseUrl: FfiConverterOptionString.read(from: &buf), 
                defaultHeaders: FfiConverterDictionaryStringString.read(from: &buf), 
                dnsOverrides: FfiConverterDictionaryStringString.read(from: &buf), 
                certificatePins: FfiConverterDictionaryStringSequenceString.read(from: &buf), 
                cookiesEnabled: FfiConverterBool.read(from: &buf), 
                cookiePersistencePath: FfiConverterOptionString.read(from: &buf), 
                connectionPoolEnabled: FfiConverterBool.read(from: &buf), 
                maxIdleConnections: FfiConverterUInt64.read(from: &buf), 
                connectionIdleTimeoutSeconds: FfiConverterUInt64.read(from: &buf), 
                retryMaxAttempts: FfiConverterUInt64.read(from: &buf), 
                retryInitialDelayMillis: FfiConverterUInt64.read(from: &buf), 
                retryMaxDelayMillis: FfiConverterUInt64.read(from: &buf), 
                retryUnsafeMethods: FfiConverterBool.read(from: &buf), 
                maxRequestBodyBytes: FfiConverterUInt64.read(from: &buf), 
                maxResponseBodyBytes: FfiConverterUInt64.read(from: &buf), 
                timeoutSeconds: FfiConverterOptionUInt64.read(from: &buf), 
                followRedirects: FfiConverterBool.read(from: &buf), 
                userAgent: FfiConverterOptionString.read(from: &buf), 
                protocolMode: FfiConverterTypeVaneProtocolMode.read(from: &buf), 
                proxyUrl: FfiConverterOptionString.read(from: &buf), 
                proxyAuthorization: FfiConverterOptionString.read(from: &buf), 
                maxRedirects: FfiConverterUInt32.read(from: &buf), 
                tlsMinVersion: FfiConverterOptionTypeVaneTlsVersion.read(from: &buf), 
                tlsMaxVersion: FfiConverterOptionTypeVaneTlsVersion.read(from: &buf), 
                customRootCertificates: FfiConverterSequenceString.read(from: &buf), 
                clientCertificate: FfiConverterOptionTypeVaneClientCertificate.read(from: &buf)
        )
    }

    public static func write(_ value: VaneClientConfig, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.baseUrl, into: &buf)
        FfiConverterDictionaryStringString.write(value.defaultHeaders, into: &buf)
        FfiConverterDictionaryStringString.write(value.dnsOverrides, into: &buf)
        FfiConverterDictionaryStringSequenceString.write(value.certificatePins, into: &buf)
        FfiConverterBool.write(value.cookiesEnabled, into: &buf)
        FfiConverterOptionString.write(value.cookiePersistencePath, into: &buf)
        FfiConverterBool.write(value.connectionPoolEnabled, into: &buf)
        FfiConverterUInt64.write(value.maxIdleConnections, into: &buf)
        FfiConverterUInt64.write(value.connectionIdleTimeoutSeconds, into: &buf)
        FfiConverterUInt64.write(value.retryMaxAttempts, into: &buf)
        FfiConverterUInt64.write(value.retryInitialDelayMillis, into: &buf)
        FfiConverterUInt64.write(value.retryMaxDelayMillis, into: &buf)
        FfiConverterBool.write(value.retryUnsafeMethods, into: &buf)
        FfiConverterUInt64.write(value.maxRequestBodyBytes, into: &buf)
        FfiConverterUInt64.write(value.maxResponseBodyBytes, into: &buf)
        FfiConverterOptionUInt64.write(value.timeoutSeconds, into: &buf)
        FfiConverterBool.write(value.followRedirects, into: &buf)
        FfiConverterOptionString.write(value.userAgent, into: &buf)
        FfiConverterTypeVaneProtocolMode.write(value.protocolMode, into: &buf)
        FfiConverterOptionString.write(value.proxyUrl, into: &buf)
        FfiConverterOptionString.write(value.proxyAuthorization, into: &buf)
        FfiConverterUInt32.write(value.maxRedirects, into: &buf)
        FfiConverterOptionTypeVaneTlsVersion.write(value.tlsMinVersion, into: &buf)
        FfiConverterOptionTypeVaneTlsVersion.write(value.tlsMaxVersion, into: &buf)
        FfiConverterSequenceString.write(value.customRootCertificates, into: &buf)
        FfiConverterOptionTypeVaneClientCertificate.write(value.clientCertificate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneClientConfig_lift(_ buf: RustBuffer) throws -> VaneClientConfig {
    return try FfiConverterTypeVaneClientConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneClientConfig_lower(_ value: VaneClientConfig) -> RustBuffer {
    return FfiConverterTypeVaneClientConfig.lower(value)
}


/**
 * One response header occurrence: an ordered `(name, value)` pair.
 */
public struct VaneHeader: Equatable, Hashable {
    public var name: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }

    

    
}

#if compiler(>=6)
extension VaneHeader: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneHeader: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneHeader {
        return
            try VaneHeader(
                name: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: VaneHeader, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneHeader_lift(_ buf: RustBuffer) throws -> VaneHeader {
    return try FfiConverterTypeVaneHeader.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneHeader_lower(_ value: VaneHeader) -> RustBuffer {
    return FfiConverterTypeVaneHeader.lower(value)
}


public struct VaneProgressSnapshot: Equatable, Hashable {
    public var uploadSent: UInt64
    public var uploadTotal: UInt64
    public var downloadReceived: UInt64
    public var downloadTotal: UInt64
    public var done: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uploadSent: UInt64, uploadTotal: UInt64, downloadReceived: UInt64, downloadTotal: UInt64, done: Bool) {
        self.uploadSent = uploadSent
        self.uploadTotal = uploadTotal
        self.downloadReceived = downloadReceived
        self.downloadTotal = downloadTotal
        self.done = done
    }

    

    
}

#if compiler(>=6)
extension VaneProgressSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneProgressSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneProgressSnapshot {
        return
            try VaneProgressSnapshot(
                uploadSent: FfiConverterUInt64.read(from: &buf), 
                uploadTotal: FfiConverterUInt64.read(from: &buf), 
                downloadReceived: FfiConverterUInt64.read(from: &buf), 
                downloadTotal: FfiConverterUInt64.read(from: &buf), 
                done: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: VaneProgressSnapshot, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.uploadSent, into: &buf)
        FfiConverterUInt64.write(value.uploadTotal, into: &buf)
        FfiConverterUInt64.write(value.downloadReceived, into: &buf)
        FfiConverterUInt64.write(value.downloadTotal, into: &buf)
        FfiConverterBool.write(value.done, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneProgressSnapshot_lift(_ buf: RustBuffer) throws -> VaneProgressSnapshot {
    return try FfiConverterTypeVaneProgressSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneProgressSnapshot_lower(_ value: VaneProgressSnapshot) -> RustBuffer {
    return FfiConverterTypeVaneProgressSnapshot.lower(value)
}


public struct VaneRequest: Equatable, Hashable {
    public var url: String
    public var method: String
    public var headers: [String: String]
    public var queryParams: [String: String]
    public var body: Data?
    public var bodyFilePath: String?
    /**
     * A [`create_body_stream`] id: the caller pushes the body in chunks
     * instead of materializing it. Mutually exclusive with `body` and
     * `body_file_path`. A streamed body is one-shot — see the streamed-body
     * rules on retry, redirects and transport fallback in
     * `docs/upload-streaming-design.md`.
     */
    public var bodyStreamId: UInt64?
    public var responseBodyPath: String?
    public var cancelTokenId: UInt64?
    public var progressId: UInt64?
    public var timeoutSeconds: UInt64?
    public var followRedirects: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, method: String, headers: [String: String], queryParams: [String: String], body: Data?, bodyFilePath: String?, 
        /**
         * A [`create_body_stream`] id: the caller pushes the body in chunks
         * instead of materializing it. Mutually exclusive with `body` and
         * `body_file_path`. A streamed body is one-shot — see the streamed-body
         * rules on retry, redirects and transport fallback in
         * `docs/upload-streaming-design.md`.
         */bodyStreamId: UInt64? = nil, responseBodyPath: String?, cancelTokenId: UInt64?, progressId: UInt64?, timeoutSeconds: UInt64?, followRedirects: Bool) {
        self.url = url
        self.method = method
        self.headers = headers
        self.queryParams = queryParams
        self.body = body
        self.bodyFilePath = bodyFilePath
        self.bodyStreamId = bodyStreamId
        self.responseBodyPath = responseBodyPath
        self.cancelTokenId = cancelTokenId
        self.progressId = progressId
        self.timeoutSeconds = timeoutSeconds
        self.followRedirects = followRedirects
    }

    

    
}

#if compiler(>=6)
extension VaneRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneRequest {
        return
            try VaneRequest(
                url: FfiConverterString.read(from: &buf), 
                method: FfiConverterString.read(from: &buf), 
                headers: FfiConverterDictionaryStringString.read(from: &buf), 
                queryParams: FfiConverterDictionaryStringString.read(from: &buf), 
                body: FfiConverterOptionData.read(from: &buf), 
                bodyFilePath: FfiConverterOptionString.read(from: &buf), 
                bodyStreamId: FfiConverterOptionUInt64.read(from: &buf), 
                responseBodyPath: FfiConverterOptionString.read(from: &buf), 
                cancelTokenId: FfiConverterOptionUInt64.read(from: &buf), 
                progressId: FfiConverterOptionUInt64.read(from: &buf), 
                timeoutSeconds: FfiConverterOptionUInt64.read(from: &buf), 
                followRedirects: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: VaneRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.method, into: &buf)
        FfiConverterDictionaryStringString.write(value.headers, into: &buf)
        FfiConverterDictionaryStringString.write(value.queryParams, into: &buf)
        FfiConverterOptionData.write(value.body, into: &buf)
        FfiConverterOptionString.write(value.bodyFilePath, into: &buf)
        FfiConverterOptionUInt64.write(value.bodyStreamId, into: &buf)
        FfiConverterOptionString.write(value.responseBodyPath, into: &buf)
        FfiConverterOptionUInt64.write(value.cancelTokenId, into: &buf)
        FfiConverterOptionUInt64.write(value.progressId, into: &buf)
        FfiConverterOptionUInt64.write(value.timeoutSeconds, into: &buf)
        FfiConverterBool.write(value.followRedirects, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneRequest_lift(_ buf: RustBuffer) throws -> VaneRequest {
    return try FfiConverterTypeVaneRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneRequest_lower(_ value: VaneRequest) -> RustBuffer {
    return FfiConverterTypeVaneRequest.lower(value)
}


public struct VaneResponse: Equatable, Hashable {
    public var statusCode: UInt16
    /**
     * Ordered `(name, value)` pairs, names lowercased, duplicates preserved,
     * `set-cookie` inline in arrival position — including cookies the jar
     * refused (a `Domain` that is a public suffix, or an IP literal), because
     * this reports what the server sent. On HTTP/3 this is wire order; on TCP
     * it is reqwest `HeaderMap` order (duplicates of a name grouped). The
     * redirect gate acts on the FIRST `location` occurrence (RFC 9110
     * §10.2.2); derived map views are first-wins and live binding-side.
     *
     * Redirects: the final response only. Intermediate hops still reach the
     * cookie jar as before.
     */
    public var headers: [VaneHeader]
    public var body: Data
    public var bodyFilePath: String?
    public var isSuccess: Bool
    public var url: String
    /**
     * Protocol that served the final response. `None` when no exchange
     * completed, or when the transport could not say.
     */
    public var httpVersion: VaneHttpVersion?
    /**
     * IP literal of the socket peer of the connection that produced the
     * final hop's response — `"203.0.113.7"`, `"2001:db8::1"`: no port, no
     * brackets. Direct HTTP/3: the resolved origin. Via a MASQUE (H3) or
     * CONNECT (TCP) proxy: the proxy — the actual socket peer, which is all
     * reqwest can ever report, and the H3 side matches it rather than
     * inventing a per-transport difference. `None` when the transport could
     * not say.
     */
    public var remoteIp: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(statusCode: UInt16, 
        /**
         * Ordered `(name, value)` pairs, names lowercased, duplicates preserved,
         * `set-cookie` inline in arrival position — including cookies the jar
         * refused (a `Domain` that is a public suffix, or an IP literal), because
         * this reports what the server sent. On HTTP/3 this is wire order; on TCP
         * it is reqwest `HeaderMap` order (duplicates of a name grouped). The
         * redirect gate acts on the FIRST `location` occurrence (RFC 9110
         * §10.2.2); derived map views are first-wins and live binding-side.
         *
         * Redirects: the final response only. Intermediate hops still reach the
         * cookie jar as before.
         */headers: [VaneHeader], body: Data, bodyFilePath: String?, isSuccess: Bool, url: String, 
        /**
         * Protocol that served the final response. `None` when no exchange
         * completed, or when the transport could not say.
         */httpVersion: VaneHttpVersion? = nil, 
        /**
         * IP literal of the socket peer of the connection that produced the
         * final hop's response — `"203.0.113.7"`, `"2001:db8::1"`: no port, no
         * brackets. Direct HTTP/3: the resolved origin. Via a MASQUE (H3) or
         * CONNECT (TCP) proxy: the proxy — the actual socket peer, which is all
         * reqwest can ever report, and the H3 side matches it rather than
         * inventing a per-transport difference. `None` when the transport could
         * not say.
         */remoteIp: String? = nil) {
        self.statusCode = statusCode
        self.headers = headers
        self.body = body
        self.bodyFilePath = bodyFilePath
        self.isSuccess = isSuccess
        self.url = url
        self.httpVersion = httpVersion
        self.remoteIp = remoteIp
    }

    

    
}

#if compiler(>=6)
extension VaneResponse: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneResponse {
        return
            try VaneResponse(
                statusCode: FfiConverterUInt16.read(from: &buf), 
                headers: FfiConverterSequenceTypeVaneHeader.read(from: &buf), 
                body: FfiConverterData.read(from: &buf), 
                bodyFilePath: FfiConverterOptionString.read(from: &buf), 
                isSuccess: FfiConverterBool.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                httpVersion: FfiConverterOptionTypeVaneHttpVersion.read(from: &buf), 
                remoteIp: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: VaneResponse, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.statusCode, into: &buf)
        FfiConverterSequenceTypeVaneHeader.write(value.headers, into: &buf)
        FfiConverterData.write(value.body, into: &buf)
        FfiConverterOptionString.write(value.bodyFilePath, into: &buf)
        FfiConverterBool.write(value.isSuccess, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterOptionTypeVaneHttpVersion.write(value.httpVersion, into: &buf)
        FfiConverterOptionString.write(value.remoteIp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneResponse_lift(_ buf: RustBuffer) throws -> VaneResponse {
    return try FfiConverterTypeVaneResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneResponse_lower(_ value: VaneResponse) -> RustBuffer {
    return FfiConverterTypeVaneResponse.lower(value)
}


/**
 * The variant is the machine-readable kind; every one carries the same
 * human-readable message the caller has always seen, so `Display` output and
 * catch-all handling are unchanged. `Generic` means "not classified", not
 * "internal" — new call sites may land there and callers must treat it as
 * unknown rather than as any particular failure.
 *
 * No variant carries structured detail beyond the message: a `Tls` mismatch
 * deliberately exposes no host or pin field, so error handling cannot become a
 * pin oracle.
 */
public enum VaneError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Generic(String
    )
    /**
     * The caller's request or configuration is wrong — URL, scheme, method,
     * header, body file, pin or proxy setting. Fails identically on every
     * transport.
     */
    case InvalidRequest(String
    )
    /**
     * The request's cancel token was set.
     */
    case Cancelled(String
    )
    /**
     * The connection could not be established within the deadline. Nothing
     * reached the peer, so the request is safe to replay.
     */
    case ConnectTimeout(String
    )
    /**
     * The deadline expired with the connection already up.
     */
    case Timeout(String
    )
    /**
     * Network or protocol failure: DNS, socket, QUIC, HTTP/3 framing, proxy.
     */
    case Transport(String
    )
    /**
     * Certificate verification failed, including a pin mismatch.
     */
    case Tls(String
    )
    /**
     * A request or response body exceeded the configured limit.
     */
    case BodyLimitExceeded(String
    )
    /**
     * The requested protocol is not available in this build.
     */
    case ProtocolUnsupported(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension VaneError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneError: FfiConverterRustBuffer {
    typealias SwiftType = VaneError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidRequest(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .Cancelled(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .ConnectTimeout(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .Timeout(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .Transport(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .Tls(
            try FfiConverterString.read(from: &buf)
            )
        case 8: return .BodyLimitExceeded(
            try FfiConverterString.read(from: &buf)
            )
        case 9: return .ProtocolUnsupported(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VaneError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Generic(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidRequest(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Cancelled(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ConnectTimeout(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Timeout(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Transport(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Tls(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .BodyLimitExceeded(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ProtocolUnsupported(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneError_lift(_ buf: RustBuffer) throws -> VaneError {
    return try FfiConverterTypeVaneError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneError_lower(_ value: VaneError) -> RustBuffer {
    return FfiConverterTypeVaneError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Protocol a response was actually served over, as opposed to the
 * [`VaneProtocolMode`] the request asked for.
 */

public enum VaneHttpVersion: Equatable, Hashable {
    
    case http10
    case http11
    case http2
    case http3





}

#if compiler(>=6)
extension VaneHttpVersion: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneHttpVersion: FfiConverterRustBuffer {
    typealias SwiftType = VaneHttpVersion

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneHttpVersion {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .http10
        
        case 2: return .http11
        
        case 3: return .http2
        
        case 4: return .http3
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VaneHttpVersion, into buf: inout [UInt8]) {
        switch value {
        
        
        case .http10:
            writeInt(&buf, Int32(1))
        
        
        case .http11:
            writeInt(&buf, Int32(2))
        
        
        case .http2:
            writeInt(&buf, Int32(3))
        
        
        case .http3:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneHttpVersion_lift(_ buf: RustBuffer) throws -> VaneHttpVersion {
    return try FfiConverterTypeVaneHttpVersion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneHttpVersion_lower(_ value: VaneHttpVersion) -> RustBuffer {
    return FfiConverterTypeVaneHttpVersion.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum VaneProtocolMode: Equatable, Hashable {
    
    /**
     * HTTP/3 first, falling back to HTTP/2 or HTTP/1.1 over TCP when the
     * HTTP/3 transport fails. Needs the `tcp-fallback` build feature.
     */
    case http3ThenHttp2ThenHttp1
    case http3Only
    /**
     * TCP with ALPN negotiating HTTP/2 or HTTP/1.1. Needs `tcp-fallback`.
     */
    case http2ThenHttp1
    /**
     * TCP with HTTP/2 prior knowledge. Needs `tcp-fallback`.
     */
    case http2Only
    /**
     * TCP restricted to HTTP/1.1. Needs `tcp-fallback`.
     */
    case http1Only





}

#if compiler(>=6)
extension VaneProtocolMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneProtocolMode: FfiConverterRustBuffer {
    typealias SwiftType = VaneProtocolMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneProtocolMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .http3ThenHttp2ThenHttp1
        
        case 2: return .http3Only
        
        case 3: return .http2ThenHttp1
        
        case 4: return .http2Only
        
        case 5: return .http1Only
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VaneProtocolMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .http3ThenHttp2ThenHttp1:
            writeInt(&buf, Int32(1))
        
        
        case .http3Only:
            writeInt(&buf, Int32(2))
        
        
        case .http2ThenHttp1:
            writeInt(&buf, Int32(3))
        
        
        case .http2Only:
            writeInt(&buf, Int32(4))
        
        
        case .http1Only:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneProtocolMode_lift(_ buf: RustBuffer) throws -> VaneProtocolMode {
    return try FfiConverterTypeVaneProtocolMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneProtocolMode_lower(_ value: VaneProtocolMode) -> RustBuffer {
    return FfiConverterTypeVaneProtocolMode.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum VaneTlsVersion: Equatable, Hashable {
    
    case tls12
    case tls13





}

#if compiler(>=6)
extension VaneTlsVersion: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaneTlsVersion: FfiConverterRustBuffer {
    typealias SwiftType = VaneTlsVersion

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaneTlsVersion {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .tls12
        
        case 2: return .tls13
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VaneTlsVersion, into buf: inout [UInt8]) {
        switch value {
        
        
        case .tls12:
            writeInt(&buf, Int32(1))
        
        
        case .tls13:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneTlsVersion_lift(_ buf: RustBuffer) throws -> VaneTlsVersion {
    return try FfiConverterTypeVaneTlsVersion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaneTlsVersion_lower(_ value: VaneTlsVersion) -> RustBuffer {
    return FfiConverterTypeVaneTlsVersion.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeVaneClientCertificate: FfiConverterRustBuffer {
    typealias SwiftType = VaneClientCertificate?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeVaneClientCertificate.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeVaneClientCertificate.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeVaneHttpVersion: FfiConverterRustBuffer {
    typealias SwiftType = VaneHttpVersion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeVaneHttpVersion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeVaneHttpVersion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeVaneTlsVersion: FfiConverterRustBuffer {
    typealias SwiftType = VaneTlsVersion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeVaneTlsVersion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeVaneTlsVersion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeVaneHeader: FfiConverterRustBuffer {
    typealias SwiftType = [VaneHeader]

    public static func write(_ value: [VaneHeader], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeVaneHeader.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [VaneHeader] {
        let len: Int32 = try readInt(&buf)
        var seq = [VaneHeader]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeVaneHeader.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringSequenceString: FfiConverterRustBuffer {
    public static func write(_ value: [String: [String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterSequenceString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [String]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [String]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterSequenceString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
public func cancelById(id: UInt64)  {try! rustCall() {
    uniffi_vane_fn_func_cancel_by_id(
        FfiConverterUInt64.lower(id),$0
    )
}
}
/**
 * Creates a caller-pushed request body stream and returns its id, to be set
 * as [`VaneRequest::body_stream_id`]. `content_length` of `Some(n)` sends
 * `content-length: n` and enforces exactly `n` bytes; `None` sends no length
 * (chunked on HTTP/1.1). One stream feeds exactly one request.
 */
public func createBodyStream(contentLength: UInt64?) -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_vane_fn_func_create_body_stream(
        FfiConverterOptionUInt64.lower(contentLength),$0
    )
})
}
public func createCancelToken() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_vane_fn_func_create_cancel_token($0
    )
})
}
public func createDefaultConfig() -> VaneClientConfig  {
    return try!  FfiConverterTypeVaneClientConfig_lift(try! rustCall() {
    uniffi_vane_fn_func_create_default_config($0
    )
})
}
public func createProgress() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_vane_fn_func_create_progress($0
    )
})
}
public func createVaneClient(config: VaneClientConfig)throws  -> VaneClient  {
    return try  FfiConverterTypeVaneClient_lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_func_create_vane_client(
        FfiConverterTypeVaneClientConfig_lower(config),$0
    )
})
}
/**
 * Marks the body complete. With a declared length, finishing at any other
 * byte count is an `InvalidRequest` that also fails the in-flight request.
 */
public func finishBodyStream(id: UInt64)throws   {try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_func_finish_body_stream(
        FfiConverterUInt64.lower(id),$0
    )
}
}
/**
 * Frees the id; aborts the request if the stream was not finished (and
 * releases a writer parked inside [`write_body_stream_chunk`] — this is the
 * abort path a wrapper must reach from somewhere that is not itself
 * parked). Safe on unknown or already-freed ids.
 */
public func freeBodyStream(id: UInt64)  {try! rustCall() {
    uniffi_vane_fn_func_free_body_stream(
        FfiConverterUInt64.lower(id),$0
    )
}
}
public func freeCancelToken(id: UInt64)  {try! rustCall() {
    uniffi_vane_fn_func_free_cancel_token(
        FfiConverterUInt64.lower(id),$0
    )
}
}
public func freeProgress(id: UInt64)  {try! rustCall() {
    uniffi_vane_fn_func_free_progress(
        FfiConverterUInt64.lower(id),$0
    )
}
}
public func progressSnapshotById(id: UInt64) -> VaneProgressSnapshot  {
    return try!  FfiConverterTypeVaneProgressSnapshot_lift(try! rustCall() {
    uniffi_vane_fn_func_progress_snapshot_by_id(
        FfiConverterUInt64.lower(id),$0
    )
})
}
public func responseBodyUtf8(resp: VaneResponse)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_func_response_body_utf8(
        FfiConverterTypeVaneResponse_lower(resp),$0
    )
})
}
/**
 * Appends one chunk. Blocks while the transport's send window and the
 * stream's internal buffer are full — this blocking is the backpressure, so
 * bindings run it off any thread that must stay responsive and interrupt a
 * parked call with [`free_body_stream`] (or the request's cancel token),
 * never by waiting it out. Fails once the stream or its request is dead;
 * the error is the same one the request fails with, so either side of the
 * caller learns the outcome.
 */
public func writeBodyStreamChunk(id: UInt64, chunk: Data)throws   {try rustCallWithError(FfiConverterTypeVaneError_lift) {
    uniffi_vane_fn_func_write_body_stream_chunk(
        FfiConverterUInt64.lower(id),
        FfiConverterData.lower(chunk),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_vane_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_vane_checksum_func_cancel_by_id() != 63899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_create_body_stream() != 37766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_create_cancel_token() != 2029) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_create_default_config() != 54371) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_create_progress() != 52627) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_create_vane_client() != 57471) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_finish_body_stream() != 6990) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_free_body_stream() != 41564) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_free_cancel_token() != 20515) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_free_progress() != 42043) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_progress_snapshot_by_id() != 50998) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_response_body_utf8() != 21709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_func_write_body_stream_chunk() != 63692) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_add_certificate_pin() != 4284) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_clear_certificate_pins() != 50096) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_delete_request() != 44430) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_execute_request() != 51840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_execute_streaming_request() != 17751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_get_request() != 12326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_patch_request() != 29709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_post_request() != 19674) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_put_request() != 13810) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_set_certificate_pins() != 37780) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneclient_warmup() != 42407) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneresponsestream_close_stream() != 16563) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneresponsestream_head() != 54130) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vane_checksum_method_vaneresponsestream_read_chunk() != 20515) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureVaneInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all